/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChannelInfo = IDL.Record({
  'bio' : IDL.Text,
  'subscribeUrl' : IDL.Text,
  'name' : IDL.Text,
});
export const Video = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'uploadDate' : Time,
});

export const idlService = IDL.Service({
  'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'getChannelInfo' : IDL.Func([], [ChannelInfo], ['query']),
  'getContactEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChannelInfo = IDL.Record({
    'bio' : IDL.Text,
    'subscribeUrl' : IDL.Text,
    'name' : IDL.Text,
  });
  const Video = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'uploadDate' : Time,
  });
  
  return IDL.Service({
    'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
    'getChannelInfo' : IDL.Func([], [ChannelInfo], ['query']),
    'getContactEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };